target:
	arm-hisiv200-linux-gcc  -I . login.c common.c -o login.cgi
	arm-hisiv200-linux-gcc  -I . download.c common.c -o download.cgi
	arm-hisiv200-linux-gcc  -I . snd_cmd.c common.c -o snd_cmd.cgi
	cp login.cgi download.cgi snd_cmd.cgi /home/work
