/****************************************************************************
*  
*    Copyright (c) 2005 - 2012 by Vivante Corp.  All rights reserved.
*  
*    The material in this file is confidential and contains trade secrets
*    of Vivante Corporation. This is proprietary information owned by
*    Vivante Corporation. No part of this work may be disclosed, 
*    reproduced, copied, transmitted, or used in any way for any purpose, 
*    without the express written permission of Vivante Corporation.
*  
*****************************************************************************/


#ifndef __glunname_h_
#define __glunname_h_

#if defined(_GL_11_APPENDIX)

#undef glAlphaFunc
#undef glActiveTexture
#undef glAlphaFuncx
#undef glBindBuffer
#undef glBindFramebufferOES
#undef glBindRenderbufferOES
#undef glBindTexture
#undef glBlendFunc
#undef glBufferData
#undef glBufferSubData
#undef glCheckFramebufferStatusOES
#undef glClear
#undef glClearColor
#undef glClearColorx
#undef glClearDepthf
#undef glClearDepthx
#undef glClearStencil
#undef glClientActiveTexture
#undef glClipPlanef
#undef glClipPlanex
#undef glColor4f
#undef glColor4ub
#undef glColor4x
#undef glColorMask
#undef glColorPointer
#undef glCompressedTexImage2D
#undef glCompressedTexSubImage2D
#undef glCopyTexImage2D
#undef glCopyTexSubImage2D
#undef glCullFace
#undef glCurrentPaletteMatrixOES
#undef glDeleteBuffers
#undef glDeleteFramebuffersOE
#undef glDeleteRenderbuffersOES
#undef glDeleteTextures
#undef glDepthFunc
#undef glDepthMask
#undef glDepthRangef
#undef glDepthRangex
#undef glDisable
#undef glDisableClientState
#undef glDrawArrays
#undef glDrawElements
#undef glDrawTexfOES
#undef glDrawTexfvOES
#undef glDrawTexiOES
#undef glDrawTexivOES
#undef glDrawTexsOES
#undef glDrawTexsvOES
#undef glDrawTexxOES
#undef glDrawTexxvOES
#undef glEGLImageTargetRenderbufferStorageOES
#undef glEGLImageTargetTexture2DOES
#undef glEnable
#undef glEnableClientState
#undef glFinish
#undef glFlush
#undef glFogf
#undef glFogfv
#undef glFogx
#undef glFogxv
#undef glFramebufferRenderbufferOES
#undef glFramebufferTexture2DOES
#undef glFrontFace
#undef glFrustumf
#undef glFrustumx
#undef glGenBuffers
#undef glGenerateMipmapOES
#undef glGenFramebuffersOES
#undef glGenRenderbuffersOES
#undef glGenTextures
#undef glGetBooleanv
#undef glGetBufferParameteriv
#undef glGetClipPlanef
#undef glGetClipPlanex
#undef glGetError
#undef glGetFixedv
#undef glGetFloatv
#undef glGetFramebufferAttachmentParameterivOES
#undef glGetIntegerv
#undef glGetLightfv
#undef glGetLightxv
#undef glGetMaterialfv
#undef glGetMaterialxv
#undef glGetPointerv
#undef glGetRenderbufferParameterivOES
#undef glGetString
#undef glGetTexEnvfv
#undef glGetTexEnviv
#undef glGetTexEnvxv
#undef glGetTexGenfvOES
#undef glGetTexGenivOES
#undef glGetTexGenxvOES
#undef glGetTexParameterfv
#undef glGetTexParameteriv
#undef glGetTexParameterxv
#undef glHint
#undef glIsBuffer
#undef glIsEnabled
#undef glIsFramebufferOES
#undef glIsRenderbufferOES
#undef glIsTexture
#undef glLightModelf
#undef glLightModelfv
#undef glLightModelx
#undef glLightModelxv
#undef glLightf
#undef glLightfv
#undef glLightx
#undef glLightxv
#undef glLineWidth
#undef glLineWidthx
#undef glLoadIdentity
#undef glLoadMatrixf
#undef glLoadMatrixx
#undef glLoadPaletteFromModelViewMatrixOES
#undef glLogicOp
#undef glMaterialf
#undef glMaterialfv
#undef glMaterialx
#undef glMaterialxv
#undef glMatrixIndexPointerOE
#undef glMatrixMode
#undef glMultMatrixf
#undef glMultMatrixx
#undef glMultiTexCoord4f
#undef glMultiTexCoord4x
#undef glNormal3f
#undef glNormal3x
#undef glNormalPointer
#undef glOrthof
#undef glOrthox
#undef glPixelStorei
#undef glPointParameterf
#undef glPointParameterfv
#undef glPointParameterx
#undef glPointParameterxv
#undef glPointSize
#undef glPointSizePointerOES
#undef glPointSizex
#undef glPolygonOffset
#undef glPolygonOffsetx
#undef glPopMatrix
#undef glPushMatrix
#undef glQueryMatrixxOES
#undef glReadPixels
#undef glRenderbufferStorageOES
#undef glRotatef
#undef glRotatex
#undef glSampleCoverage
#undef glSampleCoveragex
#undef glScalef
#undef glScalex
#undef glScissor
#undef glShadeModel
#undef glStencilFunc
#undef glStencilMask
#undef glStencilOp
#undef glTexCoordPointer
#undef glTexDirectInvalidateVIV
#undef glTexDirectVIV
#undef glTexEnvf
#undef glTexEnvfv
#undef glTexEnvi
#undef glTexEnviv
#undef glTexEnvx
#undef glTexEnvxv
#undef glTexGenfOES
#undef glTexGenfvOES
#undef glTexGeniOES
#undef glTexGenivOES
#undef glTexGenxOES
#undef glTexGenxvOES
#undef glTexImage2D
#undef glTexParameterf
#undef glTexParameterfv
#undef glTexParameteri
#undef glTexParameteriv
#undef glTexParameterx
#undef glTexParameterxv
#undef glTexSubImage2D
#undef glTranslatef
#undef glTranslatex
#undef glVertexPointer
#undef glViewport
#undef glWeightPointerOES
#undef glMultiDrawArraysEXT
#undef glMultiDrawElementsEXT
#undef glMapBufferOES
#undef glUnmapBufferOES
#undef glGetBufferPointervOES

#endif /* _GL_11_APPENDIX */
#endif /* __glunname_h_ */
